- hosts: localhost
  tasks:
    - name: new file creation
      copy:
        dest: file.txt
        content: test123

    - name: new stat creation
      set_stats:
        data:
          my_variable: this is awesome

    - name: get latest terraform version id
      set_stats:
        data:
          version: "{{ my_variable | json_query('current_version') }}"
