- hosts: all
  tasks:
    - name: check id
      delegate_to: localhost
      command: id
      register: myid

    - debug:
        var: myid

    - name: new file creation
      delegate_to: localhost
      copy:
        dest: /opt/storage/{{ inventory_hostname }}.txt
        content: test123
