- hosts: localhost
  tasks:
    - name: listing files
      shell: id
      register: listing
    - name: listing
      debug:
        msg: "{{ listing.stdout }}"
    - name: new variable output
      debug:
        msg: "{{ my_variable }}"
